apiVersion: apps/v1
kind: Deployment
metadata:
  name: { { .Chart.Name } }
  namespace: academyio
  labels:
    app: { { .Chart.Name } }
spec:
  replicas: { { .Values.replicaCount } }
  selector:
    matchLabels:
      app: { { .Chart.Name } }
  template:
    metadata:
      labels:
        app: { { .Chart.Name } }
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - name: { { .Chart.Name } }
          image: "{{ .Values.dockerhubUsername }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: { { .Values.image.pullPolicy } }
          ports:
            - containerPort: { { .Values.service.targetPort } }
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: { { .Values.env.aspnetcoreEnvironment } }
            - name: SEQ_SERVER_URL
              value: { { .Values.env.seqUrl } }
          envFrom:
            - secretRef:
                name: auth-api-secret
          resources:
            requests:
              cpu: { { .Values.resources.requests.cpu | quote } }
              memory: { { .Values.resources.requests.memory | quote } }
            limits:
              cpu: { { .Values.resources.limits.cpu | quote } }
              memory: { { .Values.resources.limits.memory | quote } }
          livenessProbe:
            httpGet:
              path: /health/live
              port: { { .Values.service.targetPort } }
            initialDelaySeconds: 30
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /health/ready
              port: { { .Values.service.targetPort } }
            initialDelaySeconds: 10
            periodSeconds: 10
