apiVersion: v1
kind: Service
metadata:
  name: seq-service
  namespace: academyio
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    - port: 5341
      targetPort: 5341
      protocol: TCP
      name: ingestion
  selector:
    app: seq
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seq-deployment
  namespace: academyio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seq
  template:
    metadata:
      labels:
        app: seq
    spec:
      containers:
        - name: seq
          image: datalust/seq:latest
          ports:
            - containerPort: 80
            - containerPort: 5341
          env:
            - name: ACCEPT_EULA
              value: "Y"
