name: Auth API CI

on:
  push:
    branches: ["**"] # Dispara em qualquer branch
    paths:
      - "src/services/AcademyIO.Auth.API/**"
      - "src/building-blocks/**"
      - ".github/workflows/auth-ci.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "src/services/AcademyIO.Auth.API/**"
      - "src/building-blocks/**"
      - ".github/workflows/auth-ci.yml"

jobs:
  ci:
    uses: ./.github/workflows/ci-template.yml
    with:
      project_name: "src/services/AcademyIO.Auth.API/"
      dockerfile_path: "./src/services/AcademyIO.Auth.API/Dockerfile"
      docker_image_name: "academyio-auth-api"
    secrets: inherit
