name: BFF CI

on:
  push:
    branches: ["main"]
    paths:
      - "src/api-gateways/AcademyIO.Bff/**"
      - "src/building-blocks/**"
      - ".github/workflows/bff-ci.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "src/api-gateways/AcademyIO.Bff/**"
      - "src/building-blocks/**"
      - ".github/workflows/bff-ci.yml"

jobs:
  ci:
    uses: ./.github/workflows/ci-template.yml
    with:
      project_name: "src/api-gateways/AcademyIO.Bff/"
      dockerfile_path: "./src/api-gateways/AcademyIO.Bff/Dockerfile"
      docker_image_name: "academyio-bff"
    secrets: inherit
