name: Courses API CI

on:
  push:
    branches: ["**"] # Dispara em qualquer branch
    paths:
      - "src/services/AcademyIO.Courses.API/**"
      - "src/building-blocks/**"
      - ".github/workflows/courses-ci.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "src/services/AcademyIO.Courses.API/**"
      - "src/building-blocks/**"
      - ".github/workflows/courses-ci.yml"

jobs:
  ci:
    uses: ./.github/workflows/ci-template.yml
    with:
      project_name: "src/services/AcademyIO.Courses.API/"
      dockerfile_path: "./src/services/AcademyIO.Courses.API/Dockerfile"
      docker_image_name: "academyio-courses-api"
    secrets: inherit
