name: Students API CI

on:
  push:
    branches: ["main"]
    paths:
      - "src/services/AcademyIO.Students.API/**"
      - "src/building-blocks/**"
      - ".github/workflows/students-ci.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "src/services/AcademyIO.Students.API/**"
      - "src/building-blocks/**"
      - ".github/workflows/students-ci.yml"

jobs:
  ci:
    uses: ./.github/workflows/ci-template.yml
    with:
      project_name: "src/services/AcademyIO.Students.API/"
      dockerfile_path: "./src/services/AcademyIO.Students.API/Dockerfile"
      docker_image_name: "academyio-students-api"
    secrets: inherit
